/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2021-05-19 13:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qoosignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/신승환/Desktop/java/QooSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringTest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/qooasset.jsp", Long.valueOf(1619531350831L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1619012585268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel = \"stylesheet\" href = \"resources/css/bootstrap.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"resources/css/jquery-ui.css\">\r\n");
      out.write("<script src = \"resources/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src = \"resources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script src = \"resources/js/bootstrap.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=380, height=740, user-scalable=yes, initial-scale=1.0, maximum-scale=2.0\"/>\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/jquery-ui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("    <script src=\"./js/jquery-1.12.4.js\"></script>\r\n");
      out.write("    <script src=\"./js/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"./js/bootstrap.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("         /* 넥슨 글씨체 */\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/NEXON Lv1 Gothic OTF.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        /* 로그인 이미지 */\r\n");
      out.write("        #qoo10login {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("        #qoo10login img {\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /* 전체적인 바디 */\r\n");
      out.write("        body {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            height : 740px;\r\n");
      out.write("            background-color : #F5F6F7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #copyright {\r\n");
      out.write("            /* border : 1px solid blue; */\r\n");
      out.write("            width : 310px;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #inputid:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #inputpw:focus {\r\n");
      out.write("            outline:none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 회원가입 정보 입력하는 란 */\r\n");
      out.write("        .input_box {\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            margin: 10px auto;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 정보입력창 감싸는 영역 */\r\n");
      out.write("        .info_write {\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 진짜 정보를 입력하는 창 */\r\n");
      out.write("        .inputs_info {\r\n");
      out.write("            border: 0px solid;\r\n");
      out.write("            margin: 8px 10px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 정보입력 메인글씨 -> 아이디, 비밀번호 와 같이 상태를 표현해주는 정보를 나타내는곳*/\r\n");
      out.write("        .info_name {\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            font-weight: bolder;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* 가입하기 버튼 */\r\n");
      out.write("        #submit_button {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #submit_info {\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            background-color: #EC2E3C;\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* selected 형식모두 디자인 정해주는 클래스 */\r\n");
      out.write("        .selected_info {\r\n");
      out.write("            /* border: 1px solid blue; */\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            padding-left: 7px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id = \"qoo10login\">\r\n");
      out.write("        <img src = \"resources/images/Qoo10_Logo.png\">    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"\" method=\"post\">\r\n");
      out.write("        <div class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">아이디</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"id_input\" class = \"inputs_info\" type=\"text\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"id_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">비밀번호</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"pw_input\" class = \"inputs_info\" type=\"password\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"pw_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">비밀번호 재확인</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"pw_input_check\" class = \"inputs_info\" type=\"password\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"pw_input_check\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">이름</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"name_input\" class = \"inputs_info\" type=\"text\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"gender_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">성별</div>\r\n");
      out.write("            <select class = \"selected_info\" id = gender_selected>\r\n");
      out.write("                <option value selected >성별</option>\r\n");
      out.write("                <option value = \"M\">남자</option>\r\n");
      out.write("                <option value = \"F\">여자</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"nation_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">거주국가</div>\r\n");
      out.write("            <select class = \"selected_info\" id = nation_selected>\r\n");
      out.write("                <option value selected>선택</option>\r\n");
      out.write("                <option value = \"KR\">대한민국</option>\r\n");
      out.write("                <option value = \"CN\">중국</option>\r\n");
      out.write("                <option value = \"JP\">일본</option>\r\n");
      out.write("                <option value = \"MY\">말레이시아</option>\r\n");
      out.write("                <option value = \"SG\">싱가포르</option>\r\n");
      out.write("                <option value = \"TW\">대만</option>\r\n");
      out.write("                <option value = \"UK\">영국</option>\r\n");
      out.write("                <option value = \"US\">미국</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"phone_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">휴대전화</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"phone_number_input\" class = \"inputs_info\" type=\"text\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id = \"submit_button\">\r\n");
      out.write("            <input id = \"submit_info\" type=\"submit\" value=\"가입하기\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div id = \"copyright\">\r\n");
      out.write("        Copyright &copy; <span style=\"font-weight: bold;\">Qoo10 Corp.</span> All rights reserved.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        \r\n");
      out.write("        //select 박스 클릭해줄때 빨간테두리 생기게 해주는 기능\r\n");
      out.write("        $(\".selected_info\").focus(function(){\r\n");
      out.write("            redClickSelectedOff( $('.selected_info'), $('.info_write'),this,1);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //select 박스가 아닌 박스를 클릭해줄때 빨간테두리 생기게 해주는 기능\r\n");
      out.write("        $(\".inputs_info\").focus(function(){\r\n");
      out.write("            redClickSelectedOff( $('.selected_info'), $('.info_write'),this,0);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        //셀렉트박스, 비 셀렉트박스 클릭할때 효과\r\n");
      out.write("        function redClickSelectedOff(class_1,class_2,class_this,level) {\r\n");
      out.write("            \r\n");
      out.write("            class_1.css('border','1px solid #DADADA');\r\n");
      out.write("            class_2.css('border','1px solid #DADADA');\r\n");
      out.write("\r\n");
      out.write("            if (level == 0) {\r\n");
      out.write("                $(\"#\"+class_this.id).parent().css('border','1px solid #EC2E3C');    \r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#\"+class_this.id).css('border','1px solid #EC2E3C');\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
