/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2021-05-30 14:58:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qoosignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/신승환/Desktop/java/QooSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringTest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/qooasset.jsp", Long.valueOf(1622373748546L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1619012585268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel = \"stylesheet\" href = \"resources/css/bootstrap.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"resources/css/jquery-ui.css\">\r\n");
      out.write("<script src = \"resources/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src = \"resources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script src = \"resources/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("         /* 넥슨 글씨체 */\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/NEXON Lv1 Gothic OTF.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tselect{\r\n");
      out.write("\t\t/*ios대응*/\r\n");
      out.write("\t\t-webkit-appearance: none;\r\n");
      out.write("\t\t-moz-appearance: none; \r\n");
      out.write("\t\tappearance: none;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*화살표 배경 넣기*/\r\n");
      out.write("\t\tbackground: url('이미지경로') no-repeat 98% 50% #fff; /*화살표 select박스 오른쪽 중앙 배치,배경 흰색*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tselect::-ms-expand{ \r\n");
      out.write("\t\tdisplay:none; /* 화살표 없애기 for IE10, 11*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tinput{\r\n");
      out.write("\t\t/*ios대응*/\r\n");
      out.write("\t\tappearance: none;\r\n");
      out.write("\t\t-webkit-appearance: none;\r\n");
      out.write("\t\t-webkit-border-radius: 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=380, height=740, user-scalable=yes, initial-scale=1.0, maximum-scale=2.0\"/>\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\r\n");
      out.write("                /* 로그인 이미지 */\r\n");
      out.write("        #qoo10login {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("        #qoo10login img {\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /* 전체적인 바디 */\r\n");
      out.write("        body {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            height : 1300px;\r\n");
      out.write("            background-color : #F5F6F7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #copyright {\r\n");
      out.write("            /* border : 1px solid blue; */\r\n");
      out.write("            width : 310px;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #inputid:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #inputpw:focus {\r\n");
      out.write("            outline:none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 회원가입 정보 입력하는 란 */\r\n");
      out.write("        .input_box {\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            margin: 10px auto;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 정보입력창 감싸는 영역 */\r\n");
      out.write("        .info_write {\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            margin-bottom: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 진짜 정보를 입력하는 창 */\r\n");
      out.write("        .inputs_info {\r\n");
      out.write("            border: 0px solid;\r\n");
      out.write("            margin: 8px 10px;\r\n");
      out.write("            width: 325px;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 정보입력 메인글씨 -> 아이디, 비밀번호 와 같이 상태를 표현해주는 정보를 나타내는곳*/\r\n");
      out.write("        .info_name {\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            font-weight: bolder;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* --가입하기 버튼-- */\r\n");
      out.write("        #submit_button {\r\n");
      out.write("            /* border : 1px solid red; */\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #submit_info {\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            background-color: #EC2E3C;\r\n");
      out.write("            font-family: 'NEXON Lv1 Gothic OTF';\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("        }\r\n");
      out.write("        /* --가입하기 버튼-- */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* selected 형식모두 디자인 정해주는 클래스 */\r\n");
      out.write("        .selected_info {\r\n");
      out.write("            /* border: 1px solid blue; */\r\n");
      out.write("            outline:none;\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            padding-left: 7px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            margin-bottom:4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --생년월일 입력-- */\r\n");
      out.write("        .birth {\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin: 3px 5px;\r\n");
      out.write("            width: 110px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin-bottom: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .selected_info_birth {\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            margin : 4px auto;\r\n");
      out.write("            padding-left: 7px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        /* --생년월일 입력-- */\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        /* --이메일 입력-- */\r\n");
      out.write("        .email{\r\n");
      out.write("            border: 1px solid #DADADA;\r\n");
      out.write("            /* border:1px solid red; */\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin: 3px 0px;\r\n");
      out.write("            margin-left: 5px;\r\n");
      out.write("            width: 114px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin-bottom:4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #email_gol {\r\n");
      out.write("            /* border: 1px solid green; */\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            width: 22px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding-top : 6px;\r\n");
      out.write("            padding-left: 5px;\r\n");
      out.write("            margin: 3px 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .selected_info_email {\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            /* border: 1px solid blue; */\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            margin : 4px;\r\n");
      out.write("            /* padding-left: 0px; */\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #email_selected_site {\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            width: 90px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* --이메일 입력-- */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         /* 진짜 정보를 입력하는 창 -> 작은창 버전 */\r\n");
      out.write("        .inputs_info_small {\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            margin-left: 8px;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("            width: 93px;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 유효성 검증 */\r\n");
      out.write("        .error_next_box {\r\n");
      out.write("            /* border:1px solid red; */\r\n");
      out.write("            margin:0px auto;\r\n");
      out.write("            width:400px;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            color : red;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id = \"qoo10login\">\r\n");
      out.write("        <img src = \"resources/images/Qoo10_Logo.png\">    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"\" method=\"post\">\r\n");
      out.write("        <div class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">아이디</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"id_input\" class = \"inputs_info\" type=\"text\" name = \"id_input\" autocomplete=\"off\"></div>\r\n");
      out.write("            <div class = \"error_next_box\" id=\"iderrmsg\" style=\"display:none;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div id=\"id_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">비밀번호</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"pw_input\" class = \"inputs_info\" type=\"password\" name = \"pw_input\"></div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"pwerrmsg\" style=\"display:none;\">8~16 영문 대 소문자, 숫자, 특수문자를 사용하세요.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"pw_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">비밀번호 재확인</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"pw_input_check\" class = \"inputs_info\" type=\"password\"></div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"pwerrmsg2\" style=\"display:none;\">비밀번호가 일치하지 않습니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"pw_input_check\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">이름</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"name_input\" class = \"inputs_info\" type=\"text\" name = \"name_input\"></div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">정확한 이름을 적어주세요.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"gender_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">성별</div>\r\n");
      out.write("            <select class = \"selected_info\" id = gender_selected name = \"sex_input\">\r\n");
      out.write("                <option value selected >성별</option>\r\n");
      out.write("                <option value = \"M\">남자</option>\r\n");
      out.write("                <option value = \"F\">여자</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">정확한 이름을 적어주세요.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"nation_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">거주국가</div>\r\n");
      out.write("            <select class = \"selected_info\" id = nation_selected name = \"nation_input\">\r\n");
      out.write("                <option value selected>선택</option>\r\n");
      out.write("                <option value = \"KR\">대한민국</option>\r\n");
      out.write("                <option value = \"CN\">중국</option>\r\n");
      out.write("                <option value = \"JP\">일본</option>\r\n");
      out.write("                <option value = \"MY\">말레이시아</option>\r\n");
      out.write("                <option value = \"SG\">싱가포르</option>\r\n");
      out.write("                <option value = \"TW\">대만</option>\r\n");
      out.write("                <option value = \"UK\">영국</option>\r\n");
      out.write("                <option value = \"US\">미국</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">정확한 이름을 적어주세요.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div id=\"birth_input\" class=\"input_box\" style = \"width : 360px;\">\r\n");
      out.write("            <div class = \"info_name\">&nbsp;생년월일</div>\r\n");
      out.write("            <div class = \"birth\">\r\n");
      out.write("                <input class = \"inputs_info_small\" type=\"text\" id = \"birth_yy\" placeholder = \"YYYY\" name = \"yy_input\" maxlength=\"4\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"birth\">\r\n");
      out.write("                    <select class=\"selected_info_birth\" id = \"birth_mm\" name = \"mm_input\">\r\n");
      out.write("                        <option value seleted>선택</option>\r\n");
      out.write("                        <option value = \"1\">1월</option>\r\n");
      out.write("                        <option value = \"2\">2월</option>\r\n");
      out.write("                        <option value = \"3\">3월</option>\r\n");
      out.write("                        <option value = \"4\">4월</option>\r\n");
      out.write("                        <option value = \"5\">5월</option>\r\n");
      out.write("                        <option value = \"6\">6월</option>\r\n");
      out.write("                        <option value = \"7\">7월</option>\r\n");
      out.write("                        <option value = \"8\">8월</option>\r\n");
      out.write("                        <option value = \"9\">9월</option>\r\n");
      out.write("                        <option value = \"10\">10월</option>\r\n");
      out.write("                        <option value = \"11\">11월</option>\r\n");
      out.write("                        <option value = \"12\">12월</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"birth\">\r\n");
      out.write("                <input class = \"inputs_info_small\" type=\"text\" id = \"birth_dd\" placeholder = \"dd\" name = \"dd_input\" maxlength=\"2\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"margin-left:5px; clear:both; display:none;\">정확한 이름을 적어주세요.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"email_input\" class=\"input_box\" style = \"width : 360px;\">\r\n");
      out.write("            <div class = \"info_name\">&nbsp;이메일 주소</div>\r\n");
      out.write("            <div class = \"email\">\r\n");
      out.write("                <input class = \"inputs_info_small\" type=\"text\" id = \"email_id\" name = \"email_input_address\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id = \"email_gol\">@</div>\r\n");
      out.write("            <div class = \"email\">\r\n");
      out.write("                <input class = \"inputs_info_small\" type=\"text\" id = \"email_site\" name = \"email_input_site\">\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class = \"email\" id = \"email_selected_site\">\r\n");
      out.write("                    <select class=\"selected_info_email\" id = \"email_site_seleted\">\r\n");
      out.write("                        <option value seleted>직접입력</option>\r\n");
      out.write("                        <option value = \"naver\">naver</option>\r\n");
      out.write("                        <option value = \"gmail\">gmail</option>\r\n");
      out.write("                        <option value = \"yahoo\">yahoo</option>\r\n");
      out.write("                        <option value = \"hotmail\">hotmail</option>\r\n");
      out.write("                        <option value = \"hanmail\">hanmail</option>\r\n");
      out.write("                        <option value = \"qoo10\">qoo10</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"margin-left:5px; clear:both; display:none;\">필수입력 항목입니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"email_agree\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">이메일 발송 동의 유무</div>\r\n");
      out.write("                <select class = \"selected_info\" id = email_selected name = \"email_agree_input\">\r\n");
      out.write("                    <option value selected>선택</option>\r\n");
      out.write("                    <option value = \"Y\">동의</option>\r\n");
      out.write("                    <option value = \"N\">비동의</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">필수입력 항목입니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"phone_input\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">휴대전화</div>\r\n");
      out.write("            <div class = \"info_write\"><input id = \"phone_number_input\" class = \"inputs_info\" type=\"text\" placeholder=\"01012345678\" name = \"phone_input\" maxlength=\"11\"></div>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">필수입력 항목입니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"sms_agree\" class=\"input_box\">\r\n");
      out.write("            <div class = \"info_name\">SMS 발송 동의 유무</div>\r\n");
      out.write("                <select class = \"selected_info\" id = sms_selected name = \"sms_agree_input\">\r\n");
      out.write("                    <option value selected>선택</option>\r\n");
      out.write("                    <option value = \"Y\">동의</option>\r\n");
      out.write("                    <option value = \"N\">비동의</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            <div class=\"error_next_box\" id=\"nameerrmsg2\" style=\"display:none;\">필수입력 항목입니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div id = \"submit_button\" style=\"margin-top:50px;\">\r\n");
      out.write("            <input id = \"submit_info\" type=\"submit\" value=\"가입하기\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div id = \"copyright\">\r\n");
      out.write("        Copyright &copy; <span style=\"font-weight: bold;\">Qoo10 Corp.</span> All rights reserved.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        //----------------------------------------------------------------------------유효성 검증-----------------------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("        //1. 아이디\r\n");
      out.write("        var idFlag = false;\r\n");
      out.write("        \r\n");
      out.write("        $(\"#id_input\").blur(function(){\r\n");
      out.write("\r\n");
      out.write("            if(idFlag) return true;\r\n");
      out.write("            var id = this.value;\r\n");
      out.write("            \r\n");
      out.write("            //iderrmsg\r\n");
      out.write("            if (id == \"\") {\r\n");
      out.write("                \r\n");
      out.write("                $(\"#iderrmsg\").text('필수입력 항목입니다.');\r\n");
      out.write("                $(\"#iderrmsg\").css('display','block');\r\n");
      out.write("                return false;\r\n");
      out.write("            } \r\n");
      out.write("\r\n");
      out.write("            var isID = /^[a-z0-9][a-z0-9_\\-]{4,19}$/;\r\n");
      out.write("            if (!isID.test(id)) {\r\n");
      out.write("                \r\n");
      out.write("                $(\"#iderrmsg\").text('5~12자의 영문 소문자, 숫자와 특수기호(_)만 사용 가능합니다.');\r\n");
      out.write("                $(\"#iderrmsg\").css('display','block');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type:\"GET\",\r\n");
      out.write("                url: \"/spring/signUpId.action\" ,\r\n");
      out.write("                data : \"checkid=\" + id,\r\n");
      out.write("                datattype : \"json\",\r\n");
      out.write("                success : function(result) {\r\n");
      out.write("                    //var result = data.substr(4);\r\n");
      out.write("                    console.log(result);\r\n");
      out.write("                    \r\n");
      out.write("                    if (result == 1) {\r\n");
      out.write("                    \tconsole.log(result);\r\n");
      out.write("                        $(\"#iderrmsg\").text('멋진 아이디네요!');\r\n");
      out.write("                        $(\"#iderrmsg\").css('display','block');\r\n");
      out.write("                        /* if (event == \"first\") {\r\n");
      out.write("                            showSuccessMsg(oMsg, \"멋진 아이디네요!\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            hideMsg(oMsg);\r\n");
      out.write("                        } */\r\n");
      out.write("                        idFlag = true;\r\n");
      out.write("                    } else {\r\n");
      out.write("                    \tconsole.log(result);\r\n");
      out.write("                    \t$(\"#iderrmsg\").text('이미 사용중이거나 탈퇴한 아이디입니다.');\r\n");
      out.write("                        $(\"#iderrmsg\").css('display','block');\r\n");
      out.write("                        /* showErrorMsg(oMsg, \"이미 사용중이거나 탈퇴한 아이디입니다.\");\r\n");
      out.write("                        setFocusToInputObject(oInput); */\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function(a,b,c) {\r\n");
      out.write("                \tconsole.log(\"error\");\r\n");
      out.write("\t\t\t\t\tconsole.log(a,b,c);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            return true;\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //select 박스 클릭해줄때 빨간테두리 생기게 해주는 기능\r\n");
      out.write("        $(\".selected_info\").focus(function(){\r\n");
      out.write("            redClickSelectedOff(2,this);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //select 박스가 아닌 박스를 클릭해줄때 빨간테두리 생기게 해주는 기능\r\n");
      out.write("        $(\".inputs_info\").focus(function(){\r\n");
      out.write("            redClickSelectedOff(1,this);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#birth_yy\").focus(function(){\r\n");
      out.write("            \r\n");
      out.write("            redClickSelectedOffbirth(this.id,1);\r\n");
      out.write("            //console.log( $(\"#birth_yy\").parent());\r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#birth_mm\").focus(function(){\r\n");
      out.write("           \r\n");
      out.write("            redClickSelectedOffbirth(this.id,1);\r\n");
      out.write("            //console.log( $(\"#birth_mm\").parent());\r\n");
      out.write("           \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#birth_dd\").focus(function(){\r\n");
      out.write("\r\n");
      out.write("            redClickSelectedOffbirth(this.id,1);\r\n");
      out.write("            //console.log( $(\"#birth_dd\").parent());\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#email_id\").focus(function(){\r\n");
      out.write("            redClickSelectedOffemail(this.id,1);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#email_site\").focus(function(){\r\n");
      out.write("            redClickSelectedOffemail(this.id,1);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        $(\"#email_site_seleted\").focus(function(){\r\n");
      out.write("            redClickSelectedOffemail(this.id,1);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        //이메일주소 선택시 바로 value를 넣어주기 위한 작업\r\n");
      out.write("        $(\"#email_site_seleted\").on('change',function(){\r\n");
      out.write("\r\n");
      out.write("            var emailSite = this.value;\r\n");
      out.write("\r\n");
      out.write("            if (emailSite == \"\") {\r\n");
      out.write("                $(\"#email_site\").val(\"\"); \r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#email_site\").val(this.value + \".com\"); \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //생년월일 관련\r\n");
      out.write("        function redClickSelectedOffbirth(id,num) {\r\n");
      out.write("\r\n");
      out.write("            $(\".birth\").css('border','1px solid #DADADA');\r\n");
      out.write("            \r\n");
      out.write("            if (num == 1) {//내가 주체가 될때 -> 다른함수에서 나를 콜 하지 않은경우\r\n");
      out.write("                redClickSelectedOff(0,null);\r\n");
      out.write("                redClickSelectedOffemail(null,0);\r\n");
      out.write("                $(\"#\"+id).parent().css('border','1px solid #EC2E3C');\r\n");
      out.write("            }                   \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //이메일 관련\r\n");
      out.write("        function redClickSelectedOffemail(id,num) {\r\n");
      out.write("\r\n");
      out.write("            $(\".email\").css('border','1px solid #DADADA');\r\n");
      out.write("            \r\n");
      out.write("            if (num == 1) {//내가 주체가 될때 -> 다른함수에서 나를 콜 하지 않은경우\r\n");
      out.write("                redClickSelectedOff(0,null);\r\n");
      out.write("                redClickSelectedOffbirth(0,null);\r\n");
      out.write("                $(\"#\"+id).parent().css('border','1px solid #EC2E3C');\r\n");
      out.write("            }                   \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //기본적으로 한칸짜리 놈들\r\n");
      out.write("        function redClickSelectedOff(num,class_this) {     \r\n");
      out.write("            \r\n");
      out.write("            $('.selected_info').css('border','1px solid #DADADA');\r\n");
      out.write("            $('.info_write').css('border','1px solid #DADADA');\r\n");
      out.write("        \r\n");
      out.write("            if (num == 1) {\r\n");
      out.write("                redClickSelectedOffbirth(null,0);\r\n");
      out.write("                redClickSelectedOffemail(null,0);\r\n");
      out.write("                $(\"#\"+class_this.id).parent().css('border','1px solid #EC2E3C');  \r\n");
      out.write("            } else if (num == 2) {\r\n");
      out.write("                redClickSelectedOffbirth(null,0);\r\n");
      out.write("                redClickSelectedOffemail(null,0);\r\n");
      out.write("                $(\"#\"+class_this.id).css('border','1px solid #EC2E3C'); \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
